package com.appelis.kmp_demo.core

var testToken = "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTQ4OTg5ODIsImlhdCI6MTcxNDg5ODY4MiwiaXNzIjoiQXBwZWxpc0lkZW50aXR5UHJvdmlkZXIiLCJjbGFpbXMiOnsiYXBwZWxpcy5kZXZpY2VJZCI6IjE2OTg2IiwiYXBwZWxpcy5tb2JpbGVVc2VySWQiOiIxODU5MTcxOSIsImFwcGVsaXMucHJvamVjdElkIjoiMSJ9fQ.ynSvKZYG_FcLEezI_ro-aG7NpTzukSPKxuMcQXahR5Yfs9J4n9fevNTPjNfbNhF4rqxjl85_agRkH6ypnTS5Yw"